---
title: "Background"
format: html
---

## An Introduction to AI-VR Training Programs
VR is an effective method for organizational training, as it allows trainees to experience situations that cannot be lived in the real world due to time constraints, physical inaccessibility, dangers in the real situation, or ethical issues [@freina2015literature]. Meta-analyses have further demonstrated the effectiveness of VR training, finding that VR training is more effective over alternative training methods in both specific [@haque2006meta; @chen2020effectiveness; @howard2020meta] and general [@howard2021meta] training modalities. AI has already found benefits in traditional learning platforms, specifically  aiding in personalization, tutoring, and evaluation of e-learning platforms. Recently, researchers have begun combining similar AI applications with VR training programs. Before diving into AI-VR training, it is important to first understand VR and AI separately. 

## The Role of AI in VR Training
AI's capability in learning and development domains has resulted in several creative applications of AI in VR training. Several researchers have employed tactics similar to those used in AI e-learning (AIeL) models, using AI as an assessment tool inside of VR training programs [@bissonnette2019artificial; @yilmaz2022continuous; @sadeghi2020development]. In addition, AI-generated feedback has received much attention and implementation into VR training [@sadeghi2020development; @chen2022robot; @king2022automated; @li2020simulation]. Thanks to advancements in its ability to handle complex tasks, AI has also been incorporated into advanced non-player characters (NPCs) that help provide information to the trainee [@li2020virtual]. Researchers have also begun using AI to  utilize decision-tree logic that customizes a user’s learning experience [@ropelato2018adaptive]. AI is even being used to allow users to learn about and manipulate machine learning algorithms in virtual environments, while having   these changes affect real ML algorithms in an external Python environment [@lyu2021aiive].  These are just some of the many ways AI is being used to enhance the VR training experience, further highlighting the versatility that AI brings to this area. With so many inventive uses of AI being implemented into VR, it is no surprise that researchers are enthusiastic about the future of VR training.