---
title: "Research Questions"
format: html
---

Because technology is rapidly advancing and because the “buzz” surrounding AI-VR training encourages rushed research, one goal of this review is to identify whether best practices surrounding learning and development trainings are being applied to current AI-VR literature:

## *Research Question 1:* Are the current VR and AI training programs utilizing best practices from the science of training?\|

###      *1a. Are learning objectives created and clarified to the reader?*

Learning objectives should consist of descriptions of what trainers want to see trainees learn as a function of the training program [@ford2020learning]. Good learning objectives highlight what a trainee should show they have accomplished as a result of the training. Learning objectives should be clarified to the extent that they provide a behavior, condition, and criterion [@ford2020learning]. In this sense, a behavior refers to an objective that displays evidence of learning the desired training capability. When stating behaviors, trainers typically use verbs to describe observable actions. For example, intellectual problem-solving skills, a behavior could be specified as “discriminates by matching problems with solutions” [@ford2020learning]. A condition refers to the various factors present when assessing the desired capability. Examples of conditions may include materials or tools provided to the learner when performing the task, restrictions imposed on the learner during the task, or even physical / environmental conditions induced during the task [@ford2020learning]. The criterion refers to a set threshold or standard for acceptable performance on the learning task [@ford2020learning]. A good criterion specifies the degree of performance necessary in order to complete the training task.

An example learning objective for a session designed to train teachers on how to use a new online assessment tool could be: “Given an online assessment creation tool (condition), teachers should be able to create (behavior) a 10-item quiz within 15 minutes (criterion).” In this example, the condition is a circumstance in which trainees are provided with a specific tool (online assessment creation tool), the behavior is the creation of a quiz, and the criterion is the creation of 10-item quiz within the time limit. Good learning objectives are important to any training program, as it provides a roadmap for planning the training and clearly communicates expectations to trainees [@ford2020learning].

###      *1b. Is the training delivered in a way that builds trainees' belief in their ability to learn and display trained skills (self-efficacy).*

Research has found that self-efficacy boosts trainee motivation [@colquitt2000toward; @tracey2001influence], and motivation to learn is positively linked with increased learning outcomes and trainee satisfaction [@klein2006motivation; @tracey2001influence]. @salas2012science notes that building self-efficacy is an important component of the training process, as it puts trainees into a learning mindset. With this in mind, AI-VR training programs should contain elements that boost self-efficacy.

###      *1c. Does the training encourage trainees to participate in training to learn rather than to appear capable (promotes a learning orientation).*

Similar to building self-efficacy, promoting a learning orientation is integral to fostering the right trainee mindset [@salas2012science]. Those who engage in training with a learning orientation are found to engage in more effortful learning [@fisher1998differential], utilize adaptive metacognitive strategies [@ford1998relationships], remain focused on the training task after receiving feedback, and even display higher learning outcomes [@ford2014improving; @phillips1997role]. Furthermore, on the opposite side of the spectrum, trainees with a performance orientation may sacrifice engagement and learning outcomes in an effort to get a higher ‘score’. With the plethora of benefits afforded by utilizing a learning orientation rather than a performance orientation in training, the promotion of a learning orientation in training participants is vital to positive learning outcomes. To support a learning orientation in any training, the program’s design features should promote long-term changes in comprehension, understanding, and skills rather than place emphasis on trainee performance [@ford2020learning; @soderstrom2015learning].

###      *1d. Does the training engage trainees and build their interest?*

By building interest and fostering trainee engagement, training programs can boost a trainee’s motivation to learn [@salas2012science]. This is particularly important, as trainee motivation can boost learning outcomes and trainee reactions [@baldwin1991perils; @tannenbaum1991meeting]. Similar to building self-efficacy and promoting a learning orientation, training programs that boost trainee motivation place trainees into a learning mindset [@salas2012science]. While some features (e.g. individual traits, work environment) cannot so easily be changed to boost motivation, modifying features of an AI-VR training program is something that researchers have a vast amount of control over.

###      *1e. Does the training utilize a valid training strategy and design? This involves providing information, giving demonstrations of good and bad \| \| behaviors, allowing opportunities to practice, and providing meaningful feedback.*

Training programs should contain a valid training strategy and design, as these elements are essential to learning outcomes, especially in areas where trainees are experiencing difficulty [@salas2012science]. Historically, businesses have mostly relied on information and demonstration components when conducting organizational trainings [@patel2010]. However, @salas2012science points out that both practice and effective feedback are crucial components for learning outcomes. Because VR is safe both physically and as a mental safe space [@howard2020meta], and because AI can facilitate meaningful feedback [@kiyasseh2023multi], AI-VR training programs are poised to provide effective training strategies. Whether they currently do is something that this research question hopes to discover.

###      *1f. Does the training allow trainees to use the same cognitive processes that they will have to in the environment this learning should transfer \| to?*

Trainings that utilize the same cognitive processes as those used in the transfer environment not only increase successful transfer outcomes – they also increase sustained levels of transfer overtime [@schmidt1992new]. In other words, training that utilize the same cognitive processes as the transfer environment help trainees 1. Successfully transfer their skills, and 2. Sustain those skills longterm. @salas2012science notes that this is often due to an added level of challenge that this implementation brings to training programs. Increased levels of difficulty brought upon by this implementation allow trainees to engage in deep learning mechanisms that encourage skill mastery and long-term transfer.

###      *1g. Does the training keep trainees' attention by allowing trainees to monitor their progress toward goals?*

Training programs that utilize elements that facilitate progress monitoring encourage self-regulation among trainees. In this sense, self-regulation refers to a trainee’s ability to self-monitor their learning and performance in relation to the training goal, and the ability to adjust learning efforts as needed [@salas2012science]. Research has shown promising effects of self-regulation on both improved trainee focus [@sitzmann2010sometimes] and increased learning outcomes [@berthold2007learning; @sitzmann2009multilevel], suggesting that progress-monitoring elements could be a beneficial addition to training (Salas, 2012). The many design features offered by AI-VR training programs (sensory cues, visual user-interfaces, etc.) allow for creative and unique goal-monitoring implementations.

###      *1h. Does the training encourage trainees to make errors?*

Error encouragement is an important component of any training program not only because errors are a natural occurrence in any job, but also because it teaches error management skills that result in increased coping skills and performance [@frese1991errors]. @salas2012science recommends error encourage particularly for complex cognitive tasks, but AI-VR training programs also have the added capability of encouraging errors in training environments that, in the real world, would be unsafe and risky. With this in mind, AI-VR training programs can facilitate error encouragement on a level that traditional training programs cannot reach.

###      *1i. Does the training provide sufficient structure to trainees when allowing them to make decisions about their learning experience?*

@salas2012science notes that training programs should, to some degree, individualize the training experience for trainees. Trainees should have as much freedom in their experience as a training program can feasibly allow without detracting from learning outcomes. Training programs must have sufficient structure to facilitate user control and individualized learning experiences, as recent research has demonstrated the effectiveness of learner control on both learning processes and outcomes [@sorgenfrei2016effectiveness].

Sufficient learner control can be achieved in a variety of ways. @sorgenfrei2016effectiveness highlight several methods researchers can use to influence learner control in e-learning training programs. First, researchers can provide control over the timing and pacing of instructional events. This form of learner control allows trainees to learn somewhat asynchronously, as they can control the pace of their learning process. Second, trainees could benefit from having control over the training location, which can be easily manipulated in an e-learning environment. Third, control over navigation and design allows trainees to control the sequence and order of learning material. Fourth, control over interactions allows trainees to control the degree in which they collaborate and work with other trainees during the training process. Last, control over content and task selection allows trainees to choose the content that they wish to learn. In their literature review, @sorgenfrei2016effectiveness found that, despite minimal (or sometimes negative) effects of learner control on learner processes, cognitive and affective learning outcomes were enhanced across a variety of studies.

In recent years, research has demonstrated that AI is particularly effective at individualizing learning experiences, utilizing concepts such as decision trees to guide unique learning experiences [@matzavela2021decision; @zhou2017research]. This, combined with VR’s advanced input hardware and capability in allowing free user movement, speech, and interactivity [@howard2020meta; @howard2021meta] poises AI-VR training programs to be able to allow for more decision-making in the learning experience while still maintaining the level of structure needed to not detract from learning outcomes.

###      *1j. Does the training simulation increase psychological fidelity (e.g. job-relevant, technology used fits the task)?*

Psychological fidelity, in a training context, refers to the extent that the training program places participants into a similar psychological state as what would be felt in the transfer environment [@howard2021meta]. @salas2012science notes that increasing psychological fidelity enhances the training content’s relevance for job performance. In AI-VR training programs, psychological fidelity encapsulates more than the utilization of similar cognitive processes – it also involves a heavy emphasis towards increasing levels of immersion and presence within the simulation [@howard2021meta].

###      *1k. Does the training use established learning / outcome taxonomies (e.g. affective, cognitive, and/or behavioral indicators).*

Learning and development fields have a plethora of existing evaluation archetypes that are well received by scholars and practitioners alike. @kirkpatrick1994evaluating evaluation model is a popular evaluation framework that involves measuring trainee reactions, learning, behaviors, and results. @kirkpatrick1994evaluating considered these measurements to be ordinal, meaning that behavioral outcomes should not be measured until reaction and learning-based outcomes are assessed. Although @kirkpatrick1994evaluating’s model does have its limitations [see @salas2012science], it provides several useful evaluation comparisons and is widely used by a variety of organizations today.

Another widely popularized evaluation model comes from @kraiger1993application, who identified three notable evaluation metrics: affective, cognitive, and behavioral outcomes. The model is considered to have two main focal points. First, when developing the training program, trainers should identify the purpose for evaluation in a clear and concise manner. Only after the purpose is identified should trainers decide on the actual affective, cognitive, or behavioral evaluation components. This process helps bring clarity to the training’s purpose, and lets trainers better tailor learning outcomes to the actual purpose of the training.

The second focal point of this model relies on precision: the measures used should match the intended outcome of the training. In other words, if a training is designed to measure fire-safety outcomes [see, for example, @truong2022does], the training should not utilize a simple multiple choice test. Instead, the measurements used should align with the actual affective, cognitive, or behavioral outcome being taught. For example, when training employees on fire-safety outcomes, @kraiger1993application's model would suggest measuring this with a simulated fire scenario. When it comes to using precise measurements, AI-VR training programs are poised to perform exceptionally well, as VR creates a safe space in which trainees can participate in various scenarios that psychologically immerses them in the experience [@howard2021meta].

Furthermore, the law of accelerating returns creates issues with advancing previous research. The next technological advancement is always around the corner, meaning that it's not long before researchers abandon current tech and move onto something new. However, before moving on and building on prior research, it is important to make sure that current studies are properly testing the incremental benefits of technologies that have already been added. In this case, it is important for researchers to ensure that AI is adding value to the VR training experience before implementing the "next big thing". Therefore, it is critical that research studies compare AI-VR to VR trainings, and that they have adequate sample sizes to generalize results.

## *Research Question 2:* Are current studies on AI-enhanced VR training programs utilizing a proper control group?

A proper control group is necessary in order to determine whether or not AI is actually adding any incremental benefits to the VR training experience. This relies on the ability to make direct comparisons between AI-VR and VR-only training programs. Therefore, for the context of this research question, a proper control group refers to a VR-only (no AI component) training group.

## *Research Question 3:* Do current studies on AI-enhanced VR training programs have a sufficient number of people to make inferences about their effectiveness?

Sample sizes often vary across studies, and many researchers use unique formulas to determine sample sizes across various statistics and methodologies [see, for example, @taherdoost2017determining; @milton1986sample; @schoenfeld1983sample]. Because ideal sample sizes vary across research studies, no threshold will be set prior to reading articles. Instead, each research article’s sample size will be assessed on a case-by-case basis. Articles that have adequate sample sizes will have a number of participants that are adequate for their chosen research methodology and statistical formula. Furthermore, the research design and statistical formulas used should be those that are capable of making inferences about any particular findings effect.

Once the previous questions have been answered, it will be possible to analyze the preliminary findings of AI-enhanced VR research.

## *Research Question 4:* What are the preliminary findings: Does adding AI to VR training result in a better experience for the trainee, greater learning, or better on the job performance than regular VR training?

With research burgeoning on AI-VR training, and with contracts as large as \$20 million being given towards organizational VR training research [@talespin], it is of immense scientific and practical importance that each of these research questions are answered. With this in mind, a systematic literature review could greatly benefit AI-VR research, as it can be the first literature review to provide an overview of what AI-VR training research is doing right and where there is room for improvement. Rapid advancements in technology [@butler2016tomorrow] make it is crucial to consolidate current research into a single meta-synthesis *before* current technology becomes outdated and new research begins stacking the latest innovations onto untested technologies. AI-VR training research is interdisciplinary, making a meta-synthesis very informative for several fields. The following systematic review offers a comprehensive analysis of the current state of AI-VR training research. Specifically, this literature review aims to determine the degree to which AI-VR training research follows best practices, whether AI-VR training research utilizes a proper control group and sample size, and, if so, whether or not the preliminary findings support AI's inclusion in VR training research.
